//! Emits the TypeScript wire contract that the `@hackline/client`
//! npm package ships. Output mirrors `tests/specta_snapshot.rs` plus
//! a generated-by banner; the snapshot test guards against drift,
//! this binary is what regenerates the file consumers actually
//! import.
//!
//! Usage:
//!   cargo run -p hackline-proto --features specta --example wire_ts
//!   cargo run -p hackline-proto --features specta --example wire_ts -- <output-path>
//!
//! Default output path is `clients/hackline-ts/src/wire.ts` resolved
//! against the hackline workspace root. Lives as an example (rather
//! than a bin) so the codegen-only `specta-typescript` dep stays out
//! of normal builds — `[[example]]` targets pull in dev-dependencies,
//! `[[bin]]` targets do not.

use std::path::{Path, PathBuf};

use hackline_proto::{
    agent_info::AgentInfo,
    connect::{ConnectAck, ConnectRequest},
    event::Event,
    msg::{ApiReply, ApiRequest, CmdAck, CmdEnvelope, CmdResult, LogLevel, MsgEnvelope},
    zid::Zid,
};
use specta::TypeCollection;
use specta_typescript::{BigIntExportBehavior, Typescript};

const HEADER: &str =
    "// This file is generated by `cargo run -p hackline-proto --features specta --example wire_ts`.\n\
// Do not edit by hand. The Rust source of truth lives in the\n\
// `hackline-proto` crate. Regenerate after changing any wire type,\n\
// and commit the result.\n\
//\n\
// Scope mirrors `tests/specta_snapshot.rs`: every wire type. The\n\
// envelope `payload` fields are typed as `unknown` here — the wire\n\
// is still arbitrary JSON, the TS contract simply doesn't pretend\n\
// to know its shape (see the field comment in `src/msg.rs`).\n\n";

fn collect() -> TypeCollection {
    let mut types = TypeCollection::default();
    types
        .register_mut::<Zid>()
        .register_mut::<AgentInfo>()
        .register_mut::<ConnectRequest>()
        .register_mut::<ConnectAck>()
        .register_mut::<Event>()
        .register_mut::<LogLevel>()
        .register_mut::<CmdAck>()
        .register_mut::<CmdResult>()
        .register_mut::<MsgEnvelope>()
        .register_mut::<CmdEnvelope>()
        .register_mut::<ApiRequest>()
        .register_mut::<ApiReply>();
    types
}

fn default_output_path() -> PathBuf {
    // CARGO_MANIFEST_DIR points at crates/hackline-proto; the hackline
    // workspace root is two levels up. Computing the path means
    // `cargo run` from anywhere still writes the right file.
    let workspace_root = Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(Path::parent)
        .expect("crate manifest must be nested under the workspace root");
    workspace_root.join("clients/hackline-ts/src/wire.ts")
}

fn main() {
    let args: Vec<String> = std::env::args().collect();
    let output = args
        .get(1)
        .map(PathBuf::from)
        .unwrap_or_else(default_output_path);

    let types = collect();
    let ts = Typescript::default().bigint(BigIntExportBehavior::Number);
    let body = ts.export(&types).expect("export typescript");

    // Strip specta's per-call banner so the file leads with the
    // hackline banner above. The snapshot test still validates the
    // body text byte-for-byte.
    let body = body
        .strip_prefix(
            "// This file has been generated by Specta. Do not edit this file manually.\n",
        )
        .unwrap_or(&body);

    if let Some(parent) = output.parent() {
        std::fs::create_dir_all(parent).expect("create output dir");
    }
    let mut out = String::with_capacity(HEADER.len() + body.len());
    out.push_str(HEADER);
    out.push_str(body);

    std::fs::write(&output, &out).expect("write wire.ts");
    eprintln!("wrote {} bytes to {}", out.len(), output.display());
}
